### ISSUE TITLE
Can't build on Fedora 24

### ISSUE THREAD

**Issue by ZaWertun** [lxde/pavucontrol-qt#10]
When running `cmake` I've got this error:
```
CMake Error at CMakeLists.txt:19 (find_package):
  By not providing "FindXdgUserDirs.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "XdgUserDirs", but CMake did not find one.

  Could not find a package configuration file provided by "XdgUserDirs" with
  any of the following names:

    XdgUserDirsConfig.cmake
    xdguserdirs-config.cmake

  Add the installation prefix of "XdgUserDirs" to CMAKE_PREFIX_PATH or set
  "XdgUserDirs_DIR" to a directory containing one of the above files.  If
  "XdgUserDirs" provides a separate development package or SDK, be sure it
  has been installed.


-- Configuring incomplete, errors occurred!
```

Got any tips where I can find this cmake script?
I've tried to search it with command `dnf whatprovides '*/XdgUserDirsConfig.cmake'` with no luck.

**Comment by ZaWertun** [comment]
Managed to build pavucontrol-qt with this patch:
```diff
--- CMakeLists.txt.orig	2016-09-24 17:21:36.993841615 +0300
+++ CMakeLists.txt	2016-09-24 17:23:03.930283295 +0300
@@ -16,7 +16,6 @@
 find_package(Qt5LinguistTools REQUIRED QUIET)
 
 find_package(lxqt REQUIRED QUIET)
-find_package(XdgUserDirs REQUIRED QUIET)
 
 include(LXQtCompilerSettings NO_POLICY_SCOPE)
 include(LXQtTranslate)

```

**Comment by palinek** [comment]
The `XdgUserDirs` is part of the liblxqt(-dev) -> https://github.com/lxde/liblxqt/blob/master/cmake/find-modules/FindXdgUserDirs.cmake. I believe its include here is pointless (just a copy-paste bug).

**Comment by pmattern** [comment]
@ZaWertun 
Just FYI / to avoid confusion, two different topics are a bit mixed by now.

On the one hand there's the question whether pavucontrol-qt really has to depend on xdg-user-dirs as apparently it hasn't.

But actually this has nothing to do with the problem you ran into. Rather, you didn't install the dependencies properly.
You could have got started without any tweaking of the code by installing the non-LXQt dependencies listed in this repository's `README.md` from the Fedora repositorys (particular packages can be found in section [Prerequisites](https://github.com/lxde/lxqt/wiki/Building-from-source#prerequisites) of the wiki page addressing building from source) and installing libqtxdg and liblxqt from the sources. Basically it's of course possible to install the LXQt dependencies from the Fedora repositories, too. It's just that the versions provided in Fedora 24 are too old to fit the needs of pavucontrol-qt.
Also note that "dependencies" refers to the development files most of the time which are provided by packages `*-devel` in Fedora.

**Comment by pmattern** [comment]
(While this report pointed us to a problem in pavucontrol-qt the actual problem wasn't a bug.)
