### ISSUE TITLE
System Sounds icon isn't present

### ISSUE THREAD

**Issue by tsimonq2** [lxde/pavucontrol-qt#12]
If you look at Pavucontrol GTK, here is what it shows for the icon by `System Sounds`:

![With icon](http://storage9.static.itmages.com/i/16/0925/h_1474780445_6062683_146d31ef9f.png)

In Pavucontrol Qt, the icon is missing:

![Oh oh, no icon...](http://storage3.static.itmages.com/i/16/0925/h_1474780479_3310135_e62779b54c.png)

**Comment by pmattern** [comment]
Confirmed running `0.1.0` on Arch Linux using Adwaita, Breeze, GNOME or Oxygen suggesting the problem has nothing to do with the icon theme in use.

Among the icons according to the [Icon Naming Specification](https://www.freedesktop.org/wiki/Specifications/icon-naming-spec/) `multimedia-volume-control` seems like the one resembling its counterpart in pavucontrol (GTK) the most.
