### ISSUE TITLE
User-specific GUI settings written in same file as used by pavucontrol

### ISSUE THREAD

**Issue by pmattern** [lxde/pavucontrol-qt#19]
To save user-specific GUI settings pavucontrol-qt is using file `~/.config/pavucontrol.ini` that's used by pavucontrol as well.
I think this isn't good and pavucontrol-qt should use a file on its own, maybe just `~/config/pavucontrol-qt.ini`.

Seen running 8e61ef5 on Arch Linux.

EDIT: point out it's the *GUI* settings which are in question here.

**Comment by PCMan** [comment]
What's the problem this can create? PulseAudio settings is desktop-independent and is not really related to UI differences. Is creating yet another config file just because we change the UI toolkit really needed?

**Comment by pmattern** [comment]
The said file does not store the actual PulseAudio settings which go to `~/.config/pulse/` and should indeed be independent GUI independent. Rather, it's the settings of the GUI `pavucontrol` itself which are saved to that file.

You can see that the current situation isn't really good by reproducing the following steps. They assume both pavucontrol and pavucontrol-qt are installed in parallel which I still figure can be expected to be very common.
* Launch `pavucontrol`, change the window size, relaunch the application. The window size is restored.
* Launch `pavucontrol-qt`. The window size stored in `pavucontrol.ini` is not taken into account. Rather, the application is launched at some default window size. Change the window size, exit `pavucontrol-qt`.
* Launch `pavucontrol`. It will come up with the window size which was written to `pavucontrol.ini` by `pavucontrol-qt` upon exiting.

**Comment by palinek** [comment]
I agree with @pmattern.

**Comment by PCMan** [comment]
ok, agree.

**Comment by pmattern** [comment]
As of 4d540fa the problem addressed by this issue is solved but the solution isn't working as expected.
The window size is written in the new `$XDG_CONFIG_HOME/pavucontrol-qt/pavucontrol-qt.conf` but not sourced the next time pavucontrol-Qt is launched. Rather, the window comes up with some default size.

On a side note I wonder whether it would be feasible to store the window position in addition to its size as well.

**Comment by palinek** [comment]
> The window size is written in the new $XDG_CONFIG_HOME/pavucontrol-qt/pavucontrol-qt.conf upon exit but not sourced the next time pavucontrol-Qt is launched. Rather, the window comes up with some default size.

The saved size is "restored/used" on startup only in case it is bigger than the default size. (the same logic was used in the (gtk) pavucontrol)

**Comment by pmattern** [comment]
> The saved size is "restored/used" on startup only in case it is bigger than the default size. (the same logic was used in the (gtk) pavucontrol)

Confirmed.
But I think this behaviour does not make any sense at all. If sizes smaller than that default are considered to be avoided the GUI itself shouldn't allow for setting them in the first place. And I don't even see the point avoiding them, in particular as pavucontrol-qt automatically enables both a horizontal and a vertical scrollbar when the window gets too small.
So I definitely think we shouldn't care about the behaviour of the GTK version in this regard and restore the size that's saved upon exiting the application. The size can always be considered the one users want.

**Comment by palinek** [comment]
> So I definitely think we shouldn't care about the behaviour of the GTK version in this regard and restore the size that's saved upon exiting the application. 

please, check the #26
