### ISSUE TITLE
Option to disable adjustments past 100%

### ISSUE THREAD

**Issue by dannypotts** [lxde/pavucontrol-qt#23]
I've damaged a pair of headphones before when accidentally adjusting the volume past 0dB, fortunately I wasn't wearing them. Surely I'm not the first person to do this so an option like this in the configuration section would be great.

**Comment by agaida** [comment]
i don't know if i'm mistaken - but the option to adjust over 100% is already implemented and not activated by default. Feel free to re-open if there are any new aspects about the issue  .

**Comment by dannypotts** [comment]
Sorry for the late reply and not being clear, I meant in the gui, the lxqt panel volume control option only disables going past 100% on the selected device.

**Comment by palinek** [comment]
> Edit: Perhaps I should take this up at lxde/lxqt-panel

Yes, issues about lxqt-panel should go into lxde/lxqt
