### ISSUE TITLE
`changes-prevent` icon used for `lockToggleButton` is Adwaita theme-specific

### ISSUE THREAD

**Issue by rindeal** [lxde/pavucontrol-qt#31]
The icon is present neither in Breeze, Oxygen nor NuoveXT icon themes. There is only `changes-prevent-symbolic` present in Breeze for compatibility reasons.

I suggest to change it to an XDG standard icon `security-medium`.

**Comment by palinek** [comment]
Indeed... I was under impression that the `changes-prevent` is defined in the XDG as a standard name.

But to be correct... it isn't present only in Adwaita, but in many others (e.g. gnome, numix, highcontrast).

@lxde/lxqt are we going to use the `changes-prevent-symbolic`?
