### ISSUE TITLE
custom sinks and loopbacks don't show up

### ISSUE THREAD

**Issue by gothmog123** [lxde/pavucontrol-qt#34]
For example if you do this:
pactl load-module module-null-sink sink_name=myaudiosink
pactl load-module module-loopback 
pactl load-module module-loopback

**Comment by palinek** [comment]
> pactl load-module module-null-sink sink_name=myaudiosink

I can't confirm this one. It works correctly here and the new sink appears in GUI instantly.

> pactl load-module module-loopback

Yes, the freshly added loopbacks aren't shown in GUI.

**Comment by palinek** [comment]
> > pactl load-module module-loopback

> Yes, the freshly added loopbacks aren't shown in GUI.

Update... the playback sinks are also correctly shown.

@gothmog123 Note the combobox "Show:" on the bottom of each tab. This one defines which sinks are the user interested in.

**Comment by gothmog123** [comment]
You're right, you just have to click show all.... sorry about that.
