### ISSUE TITLE
Timeout message upon adjusting control of output device

### ISSUE THREAD

**Issue by pmattern** [lxde/pavucontrol-qt#4]
Launching fc7847e from a terminal emulator there's a bunch of timeout messages
```
[peter@arch-64-lxqt-git ~]$ TIMEOUT!
TIMEOUT!
TIMEOUT!
TIMEOUT!
TIMEOUT!
TIMEOUT!
TIMEOUT!
[...]
```
each time the controls of the current output device are adjusted.

Issue seems to be hardware and architecture independent as the findings are the same with a Realtek HDA codec on x86_64 and some AC97 virtual codec in x86_64 or i686 QEMU guests. Similarly, it doesn't matter whether or not the two channels of stereo sound are locked.
Finding can not be made with pavucontrol (GTK) on the same systems.

Couldn't see any real malfunction due to this but thought it may be worth dropping this report nevertheless.

**Comment by PCMan** [comment]
That's just a debug message which I forgot to remove.
Feel free to delete it. :-)

**Comment by palinek** [comment]
removed in @bfbd028
